-- seed categories and products (generated from the original storefront list)
insert into public.categories (id,name,blurb,image,price_list,sort) values
('bouquets','Bouquets','Rose and mixed flower bouquets for every occasion.','img/p16.jpg','roses',0),
('money','Money Bouquets','Cash bouquets styled with flowers and ribbon.','img/m52.jpg','money',1),
('balloons','Balloon Hampers','Named air balloon hampers with snacks, drinks or flowers.','img/p23.jpg','balloons',2),
('teddy','Teddy Bears','Teddy bears from 60cm up to human size.','img/m48.jpg','teddy',3),
('decor','Room Decor','Balloon and petal room surprises, by appointment.','img/m21.jpg','decor',4),
('boxes','Gift Boxes','Ready to gift boxes for him and for her.','img/p02.jpg',null,5),
('personalised','Personalised','Engraved and printed gifts with a name or photo.','img/p09.jpg',null,6),
('baby','Baby Gifts','Baskets and bouquets for new parents.','img/p12.jpg',null,7),
('footwear','Footwear','Sandals and slides, boxed and ready to gift.','img/p29.jpg',null,8);
insert into public.products (slug,name,description,category_id,image,sort) values
('p16','Signature Red Rose Bouquet','A full bouquet of red roses with baby’s breath in soft pink wrapping.','bouquets','img/p16.jpg',0),
('p03','Graduation Rose Bouquet','Red roses with a pearl finished year, a grad cap and a scroll for the graduate.','bouquets','img/p03.jpg',1),
('p23','Big Birthday Balloon Hamper','A named balloon on a box filled with snacks and treats. Add a cake if you like.','balloons','img/p23.jpg',2),
('p27','Birthday Balloon, Bouquet and Cake','A named balloon hamper, a fresh bouquet and a decorated cake in one set.','balloons','img/p27.jpg',3),
('p10','Balloon, Bouquet and Cake Set','A balloon hamper with chocolates, a rose bouquet and a cream cake.','balloons','img/p10.jpg',4),
('p22','Anniversary Balloon and Bag Set','An anniversary balloon hamper with a handbag, a bottle and a bouquet.','balloons','img/p22.jpg',5),
('p14','Thank You Wifey Set','A pink balloon hamper with chocolates, a rose cake and a bouquet.','balloons','img/p14.jpg',6),
('p26','Teddy, Balloon and Cake Surprise','A giant teddy bear, a named balloon hamper and a birthday cake.','balloons','img/p26.jpg',7),
('p20','Pink Birthday Balloon Hamper','A pink balloon hamper with drinks, snacks and a ribbon tied box.','balloons','img/p20.jpg',8),
('p00','Anniversary and Birthday Duo','Two named balloon hampers with sweets for a couple or a shared celebration.','balloons','img/p00.jpg',9),
('p07','Princess Balloon Hamper','A pink balloon hamper with a plush toy and her name on the box.','balloons','img/p07.jpg',10),
('p04','Balloon, Roses and Gold Cake','A named balloon with a red rose bouquet and a gold frosted cake.','balloons','img/p04.jpg',11),
('p02','Him Signature Box','A striped polo, belt, wallet and socks in a branded gift box.','boxes','img/p02.jpg',12),
('p05','Gentleman Polo and Wallet Box','A polo shirt, leather wallet, belt and accessories on red shred.','boxes','img/p05.jpg',13),
('p17','Executive Watch and Polo Box','Two polos, watches, a belt and a birthday card in one box.','boxes','img/p17.jpg',14),
('p18','Sneakers and Snacks Box','White sneakers, a polo, snacks and roses with a handwritten note.','boxes','img/p18.jpg',15),
('p01','Birthday Mom Luxe Box','A handbag, sandals, a cake topper and a Happy Birthday Mom card.','boxes','img/p01.jpg',16),
('p08','Her Birthday Luxe Set','A handbag, sandals, a watch set, a bottle and a birthday card.','boxes','img/p08.jpg',17),
('p06','Handbag and Bouquet Surprise','A handbag, a keepsake and a wrapped bouquet.','boxes','img/p06.jpg',18),
('p19','Fuel Voucher Gift Box','Fuel vouchers tied with satin bows in a hard gift box.','boxes','img/p19.jpg',19),
('p12','Baby Bouquet in Blue','A bouquet of baby wear with booties, a cap and a bib in soft blue tulle.','baby','img/p12.jpg',20),
('p13','Diaper Rose Bouquet','Diaper roses arranged as a bouquet with a name ribbon.','baby','img/p13.jpg',21),
('p21','Baby Care Basket','A wicker basket of baby wash, wipes and clothing essentials.','baby','img/p21.jpg',22),
('p25','Baby Boy Welcome Basket','An It’s a Boy basket with feeding and care essentials.','baby','img/p25.jpg',23),
('p09','Personalised Bottle and Wallet Set','An engraved flask, an engraved wallet and a pendant necklace with their name.','personalised','img/p09.jpg',24),
('p28','Bottle, Watch and Perfume Set','A named bottle, a watch, an engraved wallet and perfume in a black gift box.','personalised','img/p28.jpg',25),
('p11','Custom Photo Phone Cases','Your photo printed on a durable case. Send the picture and the phone model.','personalised','img/p11.jpg',26),
('p24','Statement Bracelets','Stainless steel and gold tone bracelets for him.','personalised','img/p24.jpg',27),
('p15','Cork Sandals Collection','Cork sole sandals in olive, sand, camo, navy and brown.','footwear','img/p15.jpg',28),
('p29','Premium Slides Collection','Leather slides in black, tan, grey and green, boxed and ready to gift.','footwear','img/p29.jpg',29),
('m00','Green Polo and Watch Box','A textured green polo, a gold tone watch and a leather wallet in a gift box.','boxes','img/m00.jpg',30),
('m02','Gentleman Grooming Box','Socks, a tie set, a flask and a shoe care kit in one organised box.','boxes','img/m02.jpg',31),
('m03','Engraved Wallet, Flask and Watch Set','A monogrammed wallet, an engraved bamboo flask, a watch and a belt.','personalised','img/m03.jpg',32),
('m04','Named Bottle and Jewellery Set','A named bottle with a watch, bracelet and necklace in a purple gift box.','personalised','img/m04.jpg',33),
('m06','Pink Balloon Room Surprise','Pink and red ceiling balloons with a Happy Birthday banner and a decorated bed.','decor','img/m06.jpg',34),
('m07','Colourful Slides Collection','Leather slides in bold colours, boxed and ready to gift.','footwear','img/m07.jpg',35),
('m08','Money Bouquet, Cake and Teddy Set','A money bouquet with a birthday cake, a teddy and a rose bouquet.','money','img/m08.jpg',36),
('m09','Cap and Flower Bouquets','Flower bouquets built around a cap, finished in blue, white or red roses.','bouquets','img/m09.jpg',37),
('m11','Wallet, Shades and Named Bottle Box','A leather wallet, sunglasses and a named bottle on red shred.','personalised','img/m11.jpg',38),
('m12','Pink Teddy with Rose Bouquet','A large pink teddy bear with a big red and white rose bouquet.','teddy','img/m12.jpg',39),
('m13','Girlfriend’s Day Box','Slides, a handbag, perfume, wine and a card in one gift box.','boxes','img/m13.jpg',40),
('m14','Slides and Handbag Gift Box','Leather slides and a crossbody bag in a branded gift box.','boxes','img/m14.jpg',41),
('m15','Named Rose Bouquets','Red rose bouquets with a name or message such as Wifey, Princess or My Queen.','bouquets','img/m15.jpg',42),
('m16','Teddy and Balloon Hamper','A pink teddy bear with a named Girlfriend’s Day balloon hamper.','teddy','img/m16.jpg',43),
('m17','Polo and Named Bottle Box','A polo shirt, a named bottle and snacks in a gift box.','personalised','img/m17.jpg',44),
('m18','Cream Polo and Accessories Box','A cream polo, belt, watch case and wallet with a thank you card.','boxes','img/m18.jpg',45),
('m19','Money Bouquet and Slides Box','A money flower bouquet with slides, perfume and a message card.','money','img/m19.jpg',46),
('m20','Dad Birthday Balloon and Cake','A named balloon hamper with chocolates and a matching birthday cake.','balloons','img/m20.jpg',47),
('m21','25th Birthday Red Room Setup','Red and pink balloons, heart foils, petals and a candle lit path.','decor','img/m21.jpg',48),
('m22','Love Room Surprise','Red and white ceiling balloons, a Love sign and rose petals.','decor','img/m22.jpg',49),
('m23','Engraved Notebook and Pen Set','A notebook and pen set with a portrait and message engraved on it.','personalised','img/m23.jpg',50),
('m24','Pink Ceiling Balloon Room','A pink balloon ceiling, a foil banner and a petal trimmed bed.','decor','img/m24.jpg',51),
('m25','Engraved Wallet and Flask Box','A black wallet, flask and pen set with a name engraved on each.','personalised','img/m25.jpg',52),
('m26','Named Bottle, Perfume and Jewellery Box','A named bottle, perfume, necklace and bracelet in a pink gift box.','personalised','img/m26.jpg',53),
('m27','Jersey, Watch and Wine Box','A jersey, a watch, a named bottle and a bottle of wine.','boxes','img/m27.jpg',54),
('m28','Black Balloon Birthday Room','Black balloons, a Happy Birthday banner and a rose bouquet on the bed.','decor','img/m28.jpg',55),
('m29','Green Polo and Wallet Box','A striped polo, belt and wallet with a thank you card.','boxes','img/m29.jpg',56),
('m30','Black Polo, Watch and Belt Box','A black polo, watch, belt and leather organiser.','boxes','img/m30.jpg',57),
('m31','Black and Silver Room Setup','Black balloons, a silver banner and an I Love You petal heart.','decor','img/m31.jpg',58),
('m32','White Teddy with Initial Bouquet','A big white teddy with a red rose bouquet and a letter of your choice.','teddy','img/m32.jpg',59),
('m33','Executive Notebook, Watch and Flask Box','A notebook, pen, flask, watch and belt in a black gift box.','boxes','img/m33.jpg',60),
('m34','Hot Pink Named Bottle Set','A hot pink named bottle with a watch, bracelet and necklace.','personalised','img/m34.jpg',61),
('m35','Girlfriend’s Day Balloon and Teddy','A named balloon hamper with a teddy bear and a small rose bouquet.','balloons','img/m35.jpg',62),
('m36','Watch, Bottle and Perfume Box','Watches, a necklace, perfume and a printed bottle in one box.','boxes','img/m36.jpg',63),
('m37','Mixed Flower Bouquet','A wrapped bouquet of roses, chrysanthemums and baby’s breath.','bouquets','img/m37.jpg',64),
('m38','Engraved Bracelets','Engraved and steel bracelets for him and for her.','personalised','img/m38.jpg',65),
('m39','Handbag and Slides Gift Set','A handbag and leather slides in a boxed set.','boxes','img/m39.jpg',66),
('m40','Named Jewellery and Wallet Box','A watch, bracelet, necklace and named wallet in a pink box.','personalised','img/m40.jpg',67),
('m41','Cap and Cars Bouquet','A cap and toy cars wrapped as a bouquet with roses.','bouquets','img/m41.jpg',68),
('m42','Silver Happy Birthday Room','Black and silver balloons, a foil banner and gift bags on the bed.','decor','img/m42.jpg',69),
('m43','Message Rose Bouquet','A large red rose bouquet with a message printed on the wrap.','bouquets','img/m43.jpg',70),
('m44','I’m Sorry Room Setup','Red and silver balloons, gift bags and petals for an apology surprise.','decor','img/m44.jpg',71),
('m45','Anniversary Petal Heart Room','A petal heart on the bed, foil hearts and a candle lit path.','decor','img/m45.jpg',72),
('m47','Birthday Cake and Flower Set','A red birthday cake with a wrapped flower bouquet and a gift.','bouquets','img/m47.jpg',73),
('m48','Red Teddy with Rose Bouquet','A big red teddy holding a bouquet of red and pink roses.','teddy','img/m48.jpg',74),
('m49','Happy Birthday My Love Balloon','A pink named balloon on a hamper box with red roses.','balloons','img/m49.jpg',75),
('m52','Money and Rose Bouquet','Folded notes wrapped around fresh red roses in black paper.','money','img/m52.jpg',76),
('m54','Girlfriend’s Day Balloon Hamper','A white balloon hamper with snacks, a bouquet and a card.','balloons','img/m54.jpg',77),
('m55','Hot Pink Birthday Room','Hot pink balloons, rose petals and a black Happy Birthday banner.','decor','img/m55.jpg',78),
('m56','Teddy, Balloon and Money Set','A pink teddy, a birthday balloon hamper, a cake and a money bouquet.','teddy','img/m56.jpg',79),
('m58','Chocolate Strawberry Gift Box','A Happy Birthday box of chocolate covered strawberries with bows.','boxes','img/m58.jpg',80),
('m59','Photo Phone Case','A phone case printed with a photo and a name.','personalised','img/m59.jpg',81),
('m61','Named Bottle, Wallet and Watch Set','A named bottle, a portrait wallet, a watch set and a necklace.','personalised','img/m61.jpg',82),
('m62','Pink Named Bottle and Wallet Set','A pink named bottle, a wallet and a watch set with a necklace.','personalised','img/m62.jpg',83),
('m63','Bow Tied Chocolate Gift Box','Bow tied chocolates in a long purple gift box.','boxes','img/m63.jpg',84),
('m64','Brown Polo and Wallet Box','A patterned polo and a black wallet with a thank you card.','boxes','img/m64.jpg',85);
update public.products set featured = true where slug in ('p16','m52','p23','m48','m21','p02','p09','p12');